#!/bin/bash

# ***************************************************
# Author: Jonathan Steve Roland (josterand)
# Github: https://github.com/josterand
#
# This project is licensed under the MIT License.
# Copyright (c) 2024 Jonathan Steve Roland (josterand).
# For detailed terms and conditions, please refer to
# the LICENSE file included with this project.
# ***************************************************

# rofi config
roficonfig=~/.config/rofi/appmenu/appmenu.rasi

screen1=$(xrandr -q | grep " connected" | awk '{print $1}' | head -n 1)
screen2=$(xrandr -q | grep " connected" | awk '{print $1}' | tail -n 1)

Laptop=""
Monitor=""
Dualscreen=""
rofiopt="$Laptop\n$Monitor\n$Dualscreen"

rofi=$(printf "$rofiopt" | rofi -config "$roficonfig" -dmenu -i)

[ "$screen1" = "$screen2" ] && notify-send -i "Second Screen is not connected" && exit
[ -z "$rofi" ] && exit

reload() {
    # add script to reset wallpaper and bar.
    # assuming you're setting those with wm, reloading works too.
    [ -n "$(pgrep bspwm)" ] && bspc wm -r
    #   [ -n "$(pgrep awesome)" ] && echo 'awesome.restart()' | awesome-client
}

case $rofi in
"$Laptop")
    xrandr --output "$screen1" --auto
    xrandr --output "$screen2" --off
    reload
    ;;

"$Monitor")
    xrandr --output "$screen2" --auto
    xrandr --output "$screen1" --off
    reload
    ;;

"$Dualscreen")
    xrandr --output "$screen1" --auto
    xrandr --output "$screen2" --right-of "$screen1" --auto
    reload
    ;;
esac
