[module/powermenu]
type = custom/text
; click-left = lxsession-logout -p ""

click-left = $HOME/.config/rofi/powermenu/powermenu.sh
content = %{T9}%{T-}
content-background = ${colors.red}
content-foreground = ${colors.bg}
content-padding = 1