[colors]
; Dark Themed Colors
bg = #404968
bg-alt = #293250
fg = #DEDBE4
fg-alt = #BAB3C9

; Light Themed Colors
; fg = #404968
; fg-alt = #293250
; bg = #DEDBE4
; bg-alt = #BAB3C9

; ===============================================
blue = #4675B1
blue-alt = #2C5FA0
sky = #8EACD4
sky-alt = #6386B6
red = #C85069
orange = #EBC04F
brown = #CE8E7B
white = #FFFFFF
black = #000000


shade-1 = #333452
shade-2 = #363F5C
shade-3 = #7A7B8C
shade-4 = #CACACE
shade-5 = #F8F8F8
; ===============================================
