#!/bin/sh

# ***************************************************
# Author: Jonathan Steve Roland (josterand)
# Github: https://github.com/josterand
#
# This project is licensed under the MIT License.
# Copyright (c) 2024 Jonathan Steve Roland (josterand).
# For detailed terms and conditions, please refer to
# the LICENSE file included with this project.
# ***************************************************

# Launches the application menu using rofi. Theme is placed in the rofi themes directory.
rofi -show drun -cycle false -theme ~/.config/rofi/themes/appmenu.rasi
