#!/bin/sh

# ***************************************************
# Author: Jonathan Steve Roland (josterand)
# Github: https://github.com/josterand
#
# This project is licensed under the MIT License.
# Copyright (c) 2024 Jonathan Steve Roland (josterand).
# For detailed terms and conditions, please refer to
# the LICENSE file included with this project.
# ***************************************************

# This is a script to take screenshots with scrot
# The screenshot automatically captures the entire screen without the cursor

# Create a directory to save screenshots if it doesn't exist
mkdir -p ~/Pictures/Screenshots

# Take screenshot and send notification to the user
scrot ~/Pictures/Screenshots/screenshot-%Y-%m-%d-%T.png
notify-send "Screenshot Saved!" "Image saved to ~/Pictures/Screenshots"
