## ***************************************************
## Author: Jonathan Steve Roland (josterand)
## Github: https://github.com/josterand
##
## This project is licensed under the MIT License.
## Copyright (c) 2024 Jonathan Steve Roland (josterand).
## For detailed terms and conditions, please refer to
## the LICENSE file included with this project.
## ***************************************************

[colors]
transparent_background_colors = false

[colors.primary]
background  =   "#141b1e"
foreground  =   "#dadada"

[colors.normal]
black   =   "#141b1e"
red     =   "#e57474"
green   =   "#8ccf7e"
yellow  =   "#e5c76b"
blue    =   "#67b0e8"
magenta =   "#c47fd5"
cyan    =   "#6cbfbf"
white   =   "#dadada"
