; ***************************************************
; Author: Jonathan Steve Roland (josterand)
; Github: https://github.com/josterand
;
; This project is licensed under the MIT License.
; Copyright (c) 2024 Jonathan Steve Roland (josterand).
; For detailed terms and conditions, please refer to
; the LICENSE file included with this project.
; ***************************************************

; Material Design Colorscheme
[colors]
base = #121212
surface = #1E1E1E
overlay = #232323
muted = #B0BEC5
subtle = #90A4AE
text = #FFFFFF
