[module/alsa]
type = internal/alsa
master-soundcard = default
speaker-soundcard = default
headphone-soundcard = default
master-mixer = Master
interval = 5
format-volume = <label-volume>
format-muted = <label-muted>
label-volume = "  %percentage%%"
label-muted = "  Muted"

[module/pulseaudio]
type = internal/pulseaudio
sink = alsa_output.pci-0000_03_00.6.analog-stereo
; Use PA_VOLUME_UI_MAX (~153%) if true, or PA_VOLUME_NORM (100%) if false
; Default: true
use-ui-max = false
interval = 5
format-volume = <label-volume>
label-volume = "  %percentage%%"
format-muted = <label-muted>
label-muted = "  Muted"

[module/battery]
type = internal/battery
full-at = 99
low-at = 20
; Use the following command to list batteries and adapters:
; $ ls -1 /sys/class/power_supply/
battery = BAT0
adapter = AC
poll-interval = 1
format-charging = <label-charging>
format-discharging = <label-discharging>
label-charging =  󱐋 %percentage%%
label-discharging =   %percentage%%

[module/cpu]
type = internal/cpu
interval = 1
format = <label>
format-prefix = 
label = "  %percentage%%"

[module/datetime]
type = internal/date
interval = 1
time = "󰥔  %Y-%m-%d %I:%M %p"
format = <label>
label = %time%

[module/memory]
type = internal/memory
interval = 1
format = <label>
format-prefix = 
label = "  %percentage_used%%"

[module/networkspeed]
type = internal/network
interface = wlp12s0
interval = 1
label-connected = %upspeed% %downspeed%

[module/network]
type = internal/network
interface = wlp12s0
interval = 1
unknown-as-up = true
format-connected = <label-connected>
format-disconnected = <label-disconnected>
label-connected = "󰤨  %{A1:networkmanager_dmenu &:}%essid%%{A}"
label-disconnected = "󰤭  %{A1:networkmanager_dmenu &:}Disconnected%{A}"

[module/title]
type = internal/xwindow
format = <label>
format-prefix = 
label = " %title%"
label-maxlen = 60
; When there's no window title
;; label-empty = Welcome Home, Josterand

[module/xworkspaces]
type = internal/xworkspaces
label-active = %name%
label-active-background = ${colors.background-alt}
label-active-underline= ${colors.primary}
label-active-padding = 1
label-occupied = %name%
label-occupied-padding = 1
label-urgent = %name%
label-urgent-background = ${colors.alert}
label-urgent-padding = 1
label-empty = %name%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 1